title = "NIAM 2020"
baseURL = "https://agosiewska.github.io/niam-2019/"
languageCode = "en-us"
theme = "airspace-hugo"

publishDir = "docs"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

  [params.slider]
    enable = true
    title = "NIAM 2020 - Navigated, Interpretable, and Automated Machine learning"
    subtitle = "Warsaw, 22-24 April 2020"
    bgImage = "img/slider-bg.jpg"

  [params.wrapper]
    enable = true
    image = "img/wrapper-img.png"
    title = "About NIAM 2020 Workshop"
    italic = "Warsaw, April 2020"
    paragraph = "The aim of the workshop is to integrate scientific communities interested in Navigated, Interpretable, and Automated ML."


  [params.feature]
    enable = true
    title = "More"
    bgImage = "img/feature-bg.jpg"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "Registration"
    paragraph = "Soon"
    [params.call.button]
      url = "#"
      text = "Register"
